# Generated by Django 5.0.1 on 2024-02-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('isi', models.TextField()),
                ('pilih_kategori', models.CharField(choices=[('py', 'Python'), ('js', 'Java Script'), ('css', 'Casceding style Sheet')], max_length=7)),
            ],
        ),
    ]
