# Generated by Django 5.0.1 on 2024-02-06 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.CharField(choices=[('python', 'python'), ('django', 'django'), ('springboot', 'springboot')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
